name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: visual Restore dependencies
      run: dotnet restore "visual-studio-template\RazorComponentCodeBehind\RazorComponentCodeBehind.sln"
    - name: Build
      run: dotnet build "visual-studio-template\RazorComponentCodeBehind\RazorComponentCodeBehind.sln" --no-restore 
